### ISSUE TITLE
Are you able to support the local files?

### ISSUE THREAD

**Issue by s711183122** [kartikk221/spotify-true-shuffle#12]
Because I found the local files would not be shuffled by program.
Are you able to support the Spotify local files?

**Comment by okawaffles** [comment]
I don't think the Spotify API returns local files in a playlist, as it varies between devices, so the site cannot "see" the files and add them to the shuffle pool. 

There would not be nearly enough information from the API either, considering most of the data comes form your device.

**Comment by kartikk221** [comment]
Hey, local songs are filtered out because they cannot be played using the API as @okawaffles mentioned since they are local to certain devices only.
