### ISSUE TITLE
Add cache

### ISSUE THREAD

**Issue by Sayrix** [kartikk221/spotify-true-shuffle#13]
Do you think it's possible to cache the playlist songs so it don't have to re fetch each time we open the website like in the localStorage or wtv

**Comment by kartikk221** [comment]
I tried to implement this with IndexedDB but it ended up being very laggy due to having to do JSON.parse() on a lot of songs and overall just incompatibility issues. If you figure it out, feel free to make a PR.

**Comment by Sayrix** [comment]
You should try to use localStorage, i think you can directly store JSON and not only plain text so don't need to parse it

**Comment by kartikk221** [comment]
I don't think `localStorage` supports storing JSON objects directly, at least not stable across most browsers. If you can link a reference that would be great.
