### ISSUE TITLE
Songs appear multiple times before other songs are played

### ISSUE THREAD

**Issue by matelko64** [kartikk221/spotify-true-shuffle#4]
I'm shuffling a 32 song playlist and I'm getting some strange shuffling.
![image](https://user-images.githubusercontent.com/119362196/218214315-b6a1ba1b-6615-4916-927a-1cddfd7e378a.png)
On the right I wrote how many times was a single song played. From 23 first songs there were only 11 unique ones.
Now, I know it's only a 32 song playlist but I would still expect it to cycle through every song before repeating old ones.
This also sometimes happens to me on a 364 song playlist, though it's much rarer there.

**Comment by kartikk221** [comment]
Hello, so the shuffling algorithm used is targeted to create sparse shuffling for large playlists. For playlists smaller than 50 songs there is only a simple swap shuffle that gets performed which will yield repetitions. To learn more about how the shuffle works, see the following source code: https://github.com/kartikk221/spotify-true-shuffle/blob/1af71f347482831db6767bd169904ce0870129e7/assets/js/main.js#L34-L38

 You will notice that the following steps are taken:
 1. A batch size to perform isolated shuffles is first determined which is usually 10% of the playlist size or at least 50 songs.
 2. A batch swap shuffle is performed in which essentially the songs array is shuffled in batches of the size determined in previous step in isolation.
 3. A total of 100 songs are retrieved in a random manner spread over the batch size in which essentially the algorithm decides on a random cursor for the first song and then randomly increments / loops around the total songs array with random values up to batch size. This essentially ensures that random songs are picked within at maximum batch size distance from each other hence making the algorithm pick songs equally spread out throughout the playlist.
