### ISSUE TITLE
Error when clicking the Connect With Spotify button

### ISSUE THREAD

**Issue by matelko64** [kartikk221/spotify-true-shuffle#6]
Whenever I click the Connect With Spotify button this error shows up on a blank white page:
INVALID_CLIENT: Invalid redirect URI
This has been happening for like 2 weeks

**Comment by kartikk221** [comment]
Hey, the URL for true shuffle was changed to https://spotify-true-shuffle.pages.dev/ in a recent update. Use this URL going forward and you should have no problems.
