### ISSUE TITLE
Shuffle All Liked Songs

### ISSUE THREAD

**Issue by fidhalkotta** [kartikk221/spotify-true-shuffle#7]
Hi! First of all I love the site and the functionality. Surprises me every time to hear songs I had pretty much forgotten about because Spotify doesn't shuffle properly. 

Personally I don't really have playlists, I add all songs I want to listen to my Liked Songs and shuffle that. Is there any chance you could add this as a feature? Currently I get around it by manually making a playlist of my liked songs to a big playlist. But it would be nicer if I didn't have to do that so it would include new songs I add to my liked songs.

**Comment by kartikk221** [comment]
Yeah sure. I could look into adding a playlist for "Liked Songs" I think Spotify's API has an endpoint for that so shouldn't be too hard.

**Comment by fidhalkotta** [comment]
Yep I think its this endpoint. Thanks!

https://developer.spotify.com/documentation/web-api/reference/get-users-saved-tracks

**Comment by fidhalkotta** [comment]
Hi! no particular rush on this, but any update?

**Comment by kartikk221** [comment]
Hey, I've been working on a way to cache music locally with a strategy to load songs much faster for playlists. Will ship the liked songs update alongside.

**Comment by kartikk221** [comment]
Hey, Liked Songs as a playlist has now been implemented. You should be able to shuffle music from liked music now.

**Comment by fidhalkotta** [comment]
Awesome, thank you!
