### ISSUE TITLE
Reshuffle & Play Adds to True Shuffle Playlist instead of Overwriting it

### ISSUE THREAD

**Issue by EpicGazel** [kartikk221/spotify-true-shuffle#8]
For non-premium users, each press of "Reshuffle & Play" causes tracks to be added/appended to the "True Shuffle Playlist" instead of replacing the playlist. The expected behavior would be overwriting the tracks as duplicates appear when adding to the playlist.

**Comment by kartikk221** [comment]
That's odd, It should be overwriting the songs in the existing playlist. When you say added/appended, do you mean the songs get added to the "True Shuffle Playlist" or does a whole new "True Shuffle Playlist" playlist greated each time?

**Comment by EpicGazel** [comment]
They get added the the "True Shuffle Playlist", attached is a video demo. For the record, I am not premium.

https://github.com/kartikk221/spotify-true-shuffle/assets/20029624/98ad0672-995c-448f-b854-5f9ef62fe3d0

**Comment by kartikk221** [comment]
This bug has been fixed in the recent update. Tracks should now be updated instead of appended in the temporary playlist.
